-- =============================================================================
-- MIGRACIÓN FLYWAY V2: Inserción de Datos Iniciales (Seed/Data Populator)
-- Muestra el patrón DML para pruebas de desarrollo local y Spring Batch [Unidad 3]
-- =============================================================================

INSERT INTO clientes (id, nombre, apellido, email, telefono, direccion) VALUES
(1,  'Juan',         'García',     'juan.garcia1@gmail.com',              NULL,                   'Av. Corrientes 1234'),
(2,  'María',        'Martínez',   'maria.martinez2@hotmail.com',         '+54 11 4521-3456',     NULL),
(3,  'Carlos',       'López',      'carlos.lopez3@yahoo.com',             NULL,                   NULL),
(4,  'Ana',          'Sánchez',    'ana.sanchez4@outlook.com',            NULL,                   'Calle Mitre 567'),
(5,  'Luis',         'González',   'luis.gonzalez5@gmail.com',            '+54 351 452-7890',     NULL),
(6,  'Laura',        'Rodríguez',  'laura.rodriguez6@hotmail.com',        NULL,                   NULL),
(7,  'Pedro',        'Fernández',  'pedro.fernandez7@yahoo.com',          NULL,                   'Av. Santa Fe 890'),
(8,  'Sofía',        'Pérez',      'sofia.perez8@outlook.com',            '+54 261 483-1234',     NULL),
(9,  'Miguel',       'Gómez',      'miguel.gomez9@gmail.com',             NULL,                   NULL),
(10, 'Elena',        'Ruiz',       'elena.ruiz10@hotmail.com',            NULL,                   'Calle San Martín 234'),
(11, 'Jorge',        'Díaz',       'jorge.diaz11@yahoo.com',              '+54 11 15-3421-5678',  NULL),
(12, 'Isabel',       'Hernández',  'isabel.hernandez12@outlook.com',      NULL,                   NULL),
(13, 'Roberto',      'Moreno',     'roberto.moreno13@gmail.com',          NULL,                   'Av. Rivadavia 1567'),
(14, 'Carmen',       'Torres',     'carmen.torres14@hotmail.com',         '+54 341 456-2345',     NULL),
(15, 'Diego',        'Jiménez',    'diego.jimenez15@yahoo.com',           NULL,                   NULL),
(16, 'Valentina',    'Álvarez',    'valentina.alvarez16@outlook.com',     NULL,                   'Calle Belgrano 345'),
(17, 'Andrés',       'Romero',     'andres.romero17@gmail.com',           '+54 11 4723-8901',     NULL),
(18, 'Gabriela',     'Navarro',    'gabriela.navarro18@hotmail.com',      NULL,                   NULL),
(19, 'Fernando',     'Domínguez',  'fernando.dominguez19@yahoo.com',      NULL,                   'Av. 9 de Julio 2800'),
(20, 'Lucía',        'Ramos',      'lucia.ramos20@outlook.com',           '+54 351 389-4567',     NULL),
(21, 'Pablo',        'Gil',        'pablo.gil21@gmail.com',               NULL,                   NULL),
(22, 'Martina',      'Serrano',    'martina.serrano22@hotmail.com',       NULL,                   'Calle Florida 678'),
(23, 'Sergio',       'Blanco',     'sergio.blanco23@yahoo.com',           '+54 261 412-9876',     NULL),
(24, 'Claudia',      'Molina',     'claudia.molina24@outlook.com',        NULL,                   NULL),
(25, 'Alejandro',    'Castro',     'alejandro.castro25@gmail.com',        NULL,                   'Av. Callao 1234'),
(26, 'Natalia',      'Ortiz',      'natalia.ortiz26@hotmail.com',         '+54 11 15-6234-7890',  NULL),
(27, 'Ricardo',      'Rubio',      'ricardo.rubio27@yahoo.com',           NULL,                   NULL),
(28, 'Paola',        'Marín',      'paola.marin28@outlook.com',           NULL,                   'Calle Lavalle 456'),
(29, 'Antonio',      'Sanz',       'antonio.sanz29@gmail.com',            '+54 341 523-1234',     NULL),
(30, 'Verónica',     'Núñez',      'veronica.nunez30@hotmail.com',        NULL,                   NULL),
(31, 'David',        'Vega',       'david.vega31@yahoo.com',              NULL,                   'Av. Entre Ríos 789'),
(32, 'Patricia',     'Herrera',    'patricia.herrera32@outlook.com',      '+54 11 4891-2345',     NULL),
(33, 'Javier',       'Peña',       'javier.pena33@gmail.com',             NULL,                   NULL),
(34, 'Mónica',       'Mendoza',    'monica.mendoza34@hotmail.com',        NULL,                   'Calle Tucumán 123'),
(35, 'Eduardo',      'Acosta',     'eduardo.acosta35@yahoo.com',          '+54 351 467-8901',     NULL),
(36, 'Silvia',       'Cabrera',    'silvia.cabrera36@outlook.com',        NULL,                   NULL),
(37, 'Manuel',       'Ríos',       'manuel.rios37@gmail.com',             NULL,                   'Av. Córdoba 2345'),
(38, 'Beatriz',      'Vargas',     'beatriz.vargas38@hotmail.com',        '+54 261 498-3456',     NULL),
(39, 'Ramón',        'Medina',     'ramon.medina39@yahoo.com',            NULL,                   NULL),
(40, 'Rosa',         'Guerrero',   'rosa.guerrero40@outlook.com',         NULL,                   'Calle Sarmiento 890'),
(41, 'Facundo',      'Suárez',     'facundo.suarez41@gmail.com',          '+54 11 15-4512-6789',  NULL),
(42, 'Agustina',     'Gutiérrez',  'agustina.gutierrez42@hotmail.com',    NULL,                   NULL),
(43, 'Nicolás',      'Reyes',      'nicolas.reyes43@yahoo.com',           NULL,                   'Av. Independencia 1234'),
(44, 'Carolina',     'Cortés',     'carolina.cortes44@outlook.com',       '+54 341 478-9012',     NULL),
(45, 'Tomás',        'Aguilar',    'tomas.aguilar45@gmail.com',           NULL,                   NULL),
(46, 'Florencia',    'Espinoza',   'florencia.espinoza46@hotmail.com',    NULL,                   'Calle Reconquista 567'),
(47, 'Matías',       'Fuentes',    'matias.fuentes47@yahoo.com',          '+54 11 4632-1234',     NULL),
(48, 'Romina',       'Delgado',    'romina.delgado48@outlook.com',        NULL,                   NULL),
(49, 'Gustavo',      'Rivas',      'gustavo.rivas49@gmail.com',           NULL,                   'Av. Pueyrredón 890'),
(50, 'Cecilia',      'Silva',      'cecilia.silva50@hotmail.com',         '+54 351 512-3456',     NULL),
(51, 'Hernán',       'Paredes',    'hernan.paredes51@yahoo.com',          NULL,                   NULL),
(52, 'Viviana',      'Flores',     'viviana.flores52@outlook.com',        NULL,                   'Calle Arenales 234'),
(53, 'Leandro',      'Rojas',      'leandro.rojas53@gmail.com',           '+54 261 534-7890',     NULL),
(54, 'Susana',       'Cruz',       'susana.cruz54@hotmail.com',           NULL,                   NULL),
(55, 'Cristian',     'Vera',       'cristian.vera55@yahoo.com',           NULL,                   'Av. Las Heras 567'),
(56, 'Marcela',      'Muñoz',      'marcela.munoz56@outlook.com',         '+54 11 15-7823-4567',  NULL),
(57, 'Ignacio',      'Ponce',      'ignacio.ponce57@gmail.com',           NULL,                   NULL),
(58, 'Lorena',       'Carrillo',   'lorena.carrillo58@hotmail.com',       NULL,                   'Calle Charcas 890'),
(59, 'Emilio',       'Cano',       'emilio.cano59@yahoo.com',             '+54 341 489-2345',     NULL),
(60, 'Sandra',       'Lara',       'sandra.lara60@outlook.com',           NULL,                   NULL),
(61, 'Dante',        'Salinas',    'dante.salinas61@gmail.com',           NULL,                   'Av. Cabildo 1234'),
(62, 'Liliana',      'Contreras',  'liliana.contreras62@hotmail.com',     '+54 11 4756-3456',     NULL),
(63, 'Rodrigo',      'Ibáñez',     'rodrigo.ibanez63@yahoo.com',          NULL,                   NULL),
(64, 'Alicia',       'Bravo',      'alicia.bravo64@outlook.com',          NULL,                   'Calle Juramento 567'),
(65, 'Maximiliano',  'Montoya',    'maximiliano.montoya65@gmail.com',     '+54 351 423-6789',     NULL),
(66, 'Esther',       'Pacheco',    'esther.pacheco66@hotmail.com',        NULL,                   NULL),
(67, 'Ezequiel',     'Arias',      'ezequiel.arias67@yahoo.com',          NULL,                   'Av. Maipú 890'),
(68, 'Nora',         'Vidal',      'nora.vidal68@outlook.com',            '+54 261 467-1234',     NULL),
(69, 'Sebastián',    'Campos',     'sebastian.campos69@gmail.com',        NULL,                   NULL),
(70, 'Irma',         'Castillo',   'irma.castillo70@hotmail.com',         NULL,                   'Calle Scalabrini Ortiz 234'),
(71, 'Gonzalo',      'Padilla',    'gonzalo.padilla71@yahoo.com',         '+54 11 15-5678-9012',  NULL),
(72, 'Miriam',       'Robles',     'miriam.robles72@outlook.com',         NULL,                   NULL),
(73, 'Adrián',       'Rangel',     'adrian.rangel73@gmail.com',           NULL,                   'Av. Triunvirato 1567'),
(74, 'Olga',         'Soto',       'olga.soto74@hotmail.com',             '+54 341 512-4567',     NULL),
(75, 'Esteban',      'Miranda',    'esteban.miranda75@yahoo.com',         NULL,                   NULL),
(76, 'Mariana',      'Bermúdez',   'mariana.bermudez76@outlook.com',      NULL,                   'Calle Concepción Arenal 345'),
(77, 'Federico',     'Valdes',     'federico.valdes77@gmail.com',         '+54 11 4823-5678',     NULL),
(78, 'Graciela',     'Escobar',    'graciela.escobar78@hotmail.com',      NULL,                   NULL),
(79, 'Bruno',        'Pizarro',    'bruno.pizarro79@yahoo.com',           NULL,                   'Av. Forest 890'),
(80, 'Norma',        'Andrade',    'norma.andrade80@outlook.com',         '+54 351 498-1234',     NULL),
(81, 'Mauricio',     'Benítez',    'mauricio.benitez81@gmail.com',        NULL,                   NULL),
(82, 'Teresa',       'Villanueva', 'teresa.villanueva82@hotmail.com',     NULL,                   'Calle Zapata 678'),
(83, 'Damián',       'Vázquez',    'damian.vazquez83@yahoo.com',          '+54 261 412-5678',     NULL),
(84, 'Elvira',       'Espejo',     'elvira.espejo84@outlook.com',         NULL,                   NULL),
(85, 'Ariel',        'Prieto',     'ariel.prieto85@gmail.com',            NULL,                   'Av. Álvarez Thomas 1234'),
(86, 'Gloria',       'Moya',       'gloria.moya86@hotmail.com',           '+54 11 15-6789-0123',  NULL),
(87, 'Ramiro',       'Luna',       'ramiro.luna87@yahoo.com',             NULL,                   NULL),
(88, 'Inés',         'Tapia',      'ines.tapia88@outlook.com',            NULL,                   'Calle Charlone 456'),
(89, 'Marcos',       'Arce',       'marcos.arce89@gmail.com',             '+54 341 534-6789',     NULL),
(90, 'Elisa',        'Calvo',      'elisa.calvo90@hotmail.com',           NULL,                   NULL),
(91, 'Lisandro',     'Palma',      'lisandro.palma91@yahoo.com',          NULL,                   'Av. Warnes 789'),
(92, 'Marta',        'Bernal',     'marta.bernal92@outlook.com',          '+54 11 4934-5678',     NULL);

-- =============================================================================
-- REAJUSTE DE SECUENCIA POSTGRESQL (Punto Crítico)
-- Al insertar IDs de forma explícita (del 1 al 92) en una columna BIGSERIAL,
-- la secuencia interna de PostgreSQL ('clientes_id_seq') NO se actualiza sola.
-- setval() ajusta el puntero al valor 92 para que el próximo @PostMapping (save)
-- genere el ID 93 y no colisione con una excepción de Clave Duplicada.
-- =============================================================================
SELECT setval('clientes_id_seq', 92);
